# Generated by Django 2.2 on 2019-04-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_title', models.CharField(max_length=200)),
                ('model_content', models.TextField()),
                ('model_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
