# Generated by Django 2.2 on 2019-05-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='grade_distribution_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GradeDistribution'),
        ),
        migrations.AlterField(
            model_name='section',
            name='grade_distribution_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GradeDistribution'),
        ),
    ]
