# Generated by Django 2.2 on 2019-05-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190507_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='course_name',
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='goal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Goal'),
        ),
        migrations.AddField(
            model_name='gradedistribution',
            name='total_student',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
