# Generated by Django 2.2 on 2019-05-07 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190507_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumcourse',
            name='goal_id',
        ),
        migrations.AddField(
            model_name='goal',
            name='course_name',
            field=models.ForeignKey(default='Database', on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
            preserve_default=False,
        ),
    ]
