# Generated by Django 2.2 on 2019-05-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190507_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
