# Generated by Django 2.2 on 2019-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190410_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='admin_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='goal_valid_credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='min_credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='units_of_topic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='A',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='A_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='A_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='B',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='B_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='B_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='C',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='C_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='C_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='D',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='D_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='D_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='Fail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='Incomplete',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='Withdraw',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='student_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')]),
        ),
    ]
