# Generated by Django 2.2 on 2019-04-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190410_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicset',
            old_name='course_name',
            new_name='assign_course_name',
        ),
        migrations.AddField(
            model_name='goal',
            name='grade_distribution_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.GradeDistribution'),
            preserve_default=False,
        ),
    ]
