# Generated by Django 2.2 on 2019-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190424_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='topic_coverage',
            field=models.CharField(choices=[('Extensive', 'Extensive'), ('Inclusive', 'Inclusive'), ('BasicPlus', 'BasicPlus'), ('Basic', 'Basic'), ('Unsatisfactory', 'Unsatisfactory'), ('Substandard', 'Substandard')], default='Basic', max_length=15),
        ),
    ]
