# Generated by Django 2.2 on 2019-05-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190505_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='TopicName',
        ),
    ]
