# Generated by Django 2.2 on 2019-05-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190505_1832'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subject_code', 'course_number'), name='unique_course'),
        ),
    ]
